// All action types are listed here:
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_ASYNC = 'GET_CHARACTERS_ASYNC';
export const REQUESTED_DATA_ERROR = 'REQUESTED_DATA_ERROR';
export const GET_FILTERED_DATA = 'GET_FILTERED_DATA';
export const REMOVE_FILTERED_DATA = 'REMOVE_FILTERED_DATA';
export const SORT_DATA_BY_ASCENDING = 'SORT_DATA_BY_ASCENDING';
export const SORT_DATA_BY_DESCENDING = 'SORT_DATA_BY_DESCENDING';
export const SEARCH_DATA = 'SEARCH_DATA';
export const ADD_FILTERED_DATA = 'ADD_FILTERED_DATA';
export const ADD_GENDER_FILTERED_DATA = 'ADD_GENDER_FILTERED_DATA';
export const REMOVE_GENDER_FILTERED_DATA = 'REMOVE_GENDER_FILTERED_DATA';
export const ADD_ORIGIN_FILTERED_DATA = 'ADD_ORIGIN_FILTERED_DATA';
export const REMOVE_ORIGIN_FILTERED_DATA = 'REMOVE_ORIGIN_FILTERED_DATA';
export const ADD_SEARCH_TEXT = 'ADD_SEARCH_TEXT';